Update README.md
ninkasisum/ninkasisum.server pull request #9
Opened 2020-07-04 19:04 UTC by oliviaboretti

2020-07-04 23:13 UTC, DiogoJunqueiraGeraldo commented on README.md
> +## Instalação
###  Não adicionar header sem descrição.

> A documentação pode expandir durante a construção do projeto, conforme essas informações aparecerem.

exemplo: [README.md](https://github.com/bkkater/Ecoleta/blob/master/README.md)

2020-07-04 23:15 UTC, DiogoJunqueiraGeraldo commented on README.md
> +## Autores
### Se possível colocar o link para o perfil do GitHub ou Linkedin de cada um dos participantes.

> Os nomes completos dos participantes devem ser adicionados no arquivo LICENSE.

exemplo: [Bianca Santos Medeiros](https://github.com/bkkater)

2020-07-04 23:17 UTC, DiogoJunqueiraGeraldo commented on README.md
> +## Estatus do Projeto
### Status

> A forma correta de escrita da palavra é status. A palavra estatus não existe no português.

2020-07-04 23:18 UTC, DiogoJunqueiraGeraldo commented on README.md
> +## Licensa
### Licença

>  O substantivo feminino licença se refere a permissão ou autorização para fazer alguma coisa

2020-07-04 23:23 UTC, DiogoJunqueiraGeraldo requested changes
#### Olá Olivia Boretti, tudo bem?

> segue revisão do P.R.

**Agradeço a contribuição.** :blush:

2020-07-05 16:12 UTC, oliviaboretti commented
Falta o linkedin da Isa
https://www.linkedin.com/in/oliviaboretti/ 
https://www.linkedin.com/in/dayana-miranda-217a02166/
https://www.linkedin.com/in/jenniaol/

2020-07-05 16:15 UTC, oliviaboretti commented
https://www.linkedin.com/in/isadorafreitas

2024-04-17 17:31 UTC, closed without merging

2024-07-12 12:56 UTC, DiogoJunqueiraGeraldo commented
Eita como programa essa galera